sudo: required
services:
    - docker
before_install:
    - docker build -t ppant/quotes-test -f ./client/Dockerfile.dev ./client

scripts:
    - docker run -e CI=true ppant/quotes-test npm run test -- --coverage

after_success:
    - docker build -t ppant/quotes ./client
    - docker build -t ppant/quotes-server ./server
    - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push ppant/quotes-server
    - docker push ppant/quotes 

deploy:
    provider: elasticbeanstalk
    region: us-east-2
    app: quotes
    env: Quotes-env
    bucket_name: elasticbeanstalk-us-east-2-963663822703
    bucket_path: quotes
    on:
        branch: master
    access_key_id: "$AWS_ACCESS_KEY"
    secret_access_key: "$AWS_SECRET_KEY"