# Docker Image which is used as foundation to create
# a custom Docker Image with this Dockerfile
FROM node:alpine

# Set workdir context
WORKDIR /app
 
# Copies package.json and package-lock.json to Docker environment
COPY ./package*.json ./
 
# Installs all node packages
RUN npm install

# Copy over the rest
COPY ./ ./
 
# Finally runs the application
CMD [ "npm", "start" ]