version: "3"
services:
    redis:
        image: redis
    react-app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - "3000:3000"
            - "3001:3001"
        volumes:
            - .:/app
        stdin_open: true
